#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.4.34f1_6a9faed444f2"
#define UNITY_VERSION_FULL_NICE "2019.4.34f1 (6a9faed444f2)"
#define UNITY_VERSION_BLD 6987694
#define UNITY_VERSION_DATE 1638921398
#define UNITY_VERSION_WIN "2019.4.34.6987694"
#define UNITY_VERSION_BRANCH "2019.4/staging"
